apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USER_NAME: mamun
  DB_USER_PASSWORD: mamun123
  DB_URL: mongodb+srv://mamun:mamun123@mlm-cluster.dsg3fod.mongodb.net/?retryWrites=true&w=majority&appName=MLM-Cluster
  PORT: "5000"
  NODE_ENV: development
  CLOUDINARY_CLOUD_NAME: dolys36wm
  CLOUDINARY_API_KEY: "372395973228638"
  CLOUDINARY_API_SECRET: TVo7BxXM5rxCkSawMsG9Rdq4D5w
  BCRYPT_SALT_ROUNDS: "10"
  JWT_SECRET: secret
  JWT_EXPIRES_IN: 1d
  JWT_REFRESH_SECRET: refreshSecret

