apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lms-backend-app
  template:
    metadata:
      labels:
        app: lms-backend-app
    spec:
      containers:
        - name: lms-backend-app
          image: docker pull mamun12/lms-backend:latest
