apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lms-backend-app
  template:
    metadata:
      app: lms-backend-app
